# Generated by Django 3.0.8 on 2020-07-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='accessory_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='bottoms',
            old_name='bottom_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='shoe_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='tops',
            old_name='top_id',
            new_name='product_id',
        ),
    ]
