# Generated by Django 3.0.8 on 2020-07-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200711_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
