# Generated by Django 3.0.8 on 2020-07-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_suppliers_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='object_id',
            new_name='product_id',
        ),
    ]
