# Generated by Django 3.0.8 on 2020-07-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200712_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='bottoms',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='tops',
            name='added_date',
        ),
    ]
