# Generated by Django 3.0.8 on 2020-07-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200712_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventory'},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
