# Generated by Django 3.0.8 on 2020-07-23 05:02

import django.core.validators
from django.db import migrations, models
import homepage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200712_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='product_color',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_name',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_type',
            field=models.CharField(default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_color',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_name',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.numeric]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_count',
            field=models.IntegerField(default=0, validators=[homepage.validators.numeric]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_color',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_name',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_firstName',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_lastName',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_title',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_address1',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_address2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_email',
            field=models.EmailField(max_length=254, validators=[homepage.validators.emailvalidator]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_website',
            field=models.URLField(validators=[homepage.validators.httpurlvalidator]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_color',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_name',
            field=models.CharField(max_length=50, validators=[homepage.validators.alphabets]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[homepage.validators.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
