# Generated by Django 3.0.8 on 2020-07-23 21:56

from django.db import migrations, models
import homepage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200723_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='product_weight',
        ),
        migrations.RemoveField(
            model_name='bottoms',
            name='product_weight',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='product_weight',
        ),
        migrations.RemoveField(
            model_name='tops',
            name='product_weight',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.min_value]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.min_value]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='added_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.min_value]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.min_value]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[homepage.validators.min_value]),
        ),
    ]
