# Generated by Django 3.0.8 on 2020-07-24 21:23

from django.db import migrations, models
import homepage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200723_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='bottoms',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact_title',
            field=models.CharField(max_length=200, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_longDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
        migrations.AlterField(
            model_name='tops',
            name='product_shortDesc',
            field=models.CharField(blank=True, max_length=50, validators=[homepage.validators.alphanumspecial]),
        ),
    ]
